name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build-wasm32-std:
    name: Build rust-std (wasm32)
    runs-on: ubuntu-22.04-arm64-large
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Checkout rust-lang/rust
        uses: actions/checkout@v6
        with:
          repository: rust-lang/rust
          ref: 1.93.0
          path: rust
          fetch-depth: 2

      - name: Copy bootstrap.toml
        run: cp bootstrap.toml rust/bootstrap.toml

      - name: Build rust-std for wasm32-unknown-unknown
        working-directory: rust
        run: ./x dist rust-std --target wasm32-unknown-unknown

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rust-std-dist-wasm32
          path: rust/build/dist
